algoritmo "Somador numerico com condicional"
var
Cont , S , N , maior: Inteiro
inicio
      Enquanto (Cont <=10) Faca
      Escreva ("Digite o ", cont ," o. valor")
      Leia (N)
      Se (N > maior) entao
         maior <- N
      Fimse
      S <- S + N
      Cont <- Cont + 1
      FimEnquanto
      Escreval (" A SOMA DE TODOS OS VALORES FOI ", S)
      Escreval (" O MAIOR VALOR DIGITADO FOI" , maior)
fimalgoritmo